<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>37e40800-0ce2-492a-829c-18ca5706116f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box-header']/div[3]/div/div[2]/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.item-bar.item-login.v-align-top > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4987e3e0-21f1-4d5a-bd33-d4dde3ae760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-US/user/login</value>
      <webElementGuid>14e68f2b-9c4b-422b-be9a-33af02768b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>042fbedb-60fb-424e-a133-aae238c3103b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-header&quot;)/div[@class=&quot;line-main&quot;]/div[@class=&quot;box-content-default content-header&quot;]/div[@class=&quot;box-right box-right-add&quot;]/div[2]/div[@class=&quot;item-bar item-login v-align-top&quot;]/a[1]</value>
      <webElementGuid>adb82198-50a8-4ff7-95d6-84766208f61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7e8fb402-f22f-4d64-8225-2c5fe7b0cff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-US/user/login</value>
      <webElementGuid>3f9a1013-bf5c-4eb7-ac25-0ffe82aca205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>db19eda7-9fc7-426e-bd5d-4f0eb79f8ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-header&quot;)/div[@class=&quot;line-main&quot;]/div[@class=&quot;box-content-default content-header&quot;]/div[@class=&quot;box-right box-right-add&quot;]/div[2]/div[@class=&quot;item-bar item-login v-align-top&quot;]/a[1]</value>
      <webElementGuid>609eeb44-2f0f-4de1-8cb6-bcf0a96ec633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29913435-977d-4f19-b157-a4edc5951a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en-US/user/login</value>
      <webElementGuid>27a447ea-2a50-493e-935c-37d244e5c8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>48d9e458-2e9d-4186-bad3-24f6170c10f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box-header&quot;)/div[@class=&quot;line-main&quot;]/div[@class=&quot;box-content-default content-header&quot;]/div[@class=&quot;box-right box-right-add&quot;]/div[2]/div[@class=&quot;item-bar item-login v-align-top&quot;]/a[1]</value>
      <webElementGuid>d4488bac-dba1-47a1-a1c7-5b44ba2bba7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box-header']/div[3]/div/div[2]/div[2]/div/a</value>
      <webElementGuid>6637b674-8b9b-4323-ad4c-65ccf8691d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Login')])[2]</value>
      <webElementGuid>9072695f-6cf9-4046-841d-618a212ffc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filipino'])[1]/following::a[1]</value>
      <webElementGuid>e3946222-a6d7-4157-ae89-f6d5334b3d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='French'])[1]/following::a[1]</value>
      <webElementGuid>f1c797bc-2ee8-40da-b038-d84ea7e5c8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[2]/preceding::a[1]</value>
      <webElementGuid>21059fcd-1dd1-4341-a476-9cf7f24c3c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[2]/preceding::a[2]</value>
      <webElementGuid>9100341b-5a90-420b-9338-1d668ba75aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/en-US/user/login')]</value>
      <webElementGuid>87782072-d703-460e-9804-8d6245d67592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>6bc89007-280f-434f-9f61-2936f0e0c73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en-US/user/login' and (text() = ' Login ' or . = ' Login ')]</value>
      <webElementGuid>0c01409e-5a23-48ff-823b-9f39ef994d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
